[package]
name = "shredder_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
# x64 disassembly and re-assembly
iced-x86 = "1.21.0"
# PE file parsing and manipulation (.exe)
exe = "0.5"
# Error handling
thiserror = "1"
rand = "0.9.2"
